server:
  #8004 表示注册到zookeeper服务器的支付服务提供者端口号
  port: 80
#服务别名 --- 注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-consumer-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?serverTimezone=UTC #?characterEncoding=utf-8&useSSL=false&useUnicode=true
    username: root
    password: 123456
  cloud:
    zookeeper:
      connect-string: 192.168.1.15:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities  #所有entity别名所在包
